### ISSUE TITLE
CI support

### ISSUE THREAD

**Issue by sbrink** [sbrink/vscode-elm#15]
Hey,

from tomorrow on I have three weeks for hacking.

We could automate the release cycle and add CI or continuous deployment.

This should be easy, we could just:

* run tests
* publish the version (vsce publish)

If the version is already published, the result will be sth. like:

vscode-elm[master*]$ vsce publish
Executing prepublish script 'node ./node_modules/vscode/bin/compile'...
Publishing sbrink.elm@0.2.1...
Error: sbrink.elm@0.2.1 already exists.

Better ideas? @rojepp @Krzysztof-Cieslak

**Comment by sbrink** [comment]
Publishing is now automated. 

Just bump the version number :)


<img width="866" alt="screen shot 2015-12-04 at 15 51 19" src="https://cloud.githubusercontent.com/assets/55469/11592490/140b8a8a-9a9f-11e5-8c8a-52ecd601ac8e.png">

**Comment by Krzysztof-Cieslak** [comment]
That's pretty cool. But personally for me, most important would be having CI server run test for each PR so we can easily see if changes are not braking anything. Would be cool if you could set up something like that.

**Comment by stkb** [comment]
What's the status of this now? I noticed a Codeship build on PR #18 but couldn't access the details. Haven't used Codeship before but [you can now run the extension build and tests on Travis](https://code.visualstudio.com/docs/extensions/testing-extensions#_running-tests-automatically-on-travis-ci-build-machines). I've done so on my own fork ([stkb/vscode-elm](https://github.com/stkb/vscode-elm))

**Comment by rojepp** [comment]
It would be good with a Travis build so anyone can see the output. I can't see the output from Codeship either.

**Comment by stkb** [comment]
Ok I've put the additions necessary to set it up in #21
