### ISSUE TITLE
REPL support

### ISSUE THREAD

**Issue by sbrink** [sbrink/vscode-elm#2]
It looks like VS Code has no support for sth. like terminal sessions.

Am I wrong? @rojepp @Krzysztof-Cieslak 

As an alternative we could execute idividual lines in a file.

**Comment by Krzysztof-Cieslak** [comment]
OK, so in F# plugin we are using Send line, Send selection and Send file and printing output from REPL to Output  Channel. 
![vscode_demo](https://cloud.githubusercontent.com/assets/5427083/11326763/422ac826-9172-11e5-8b60-be10e979631d.gif)

It's pretty easy to implement, i should be able to hack it today / tomorrow.

**Comment by sbrink** [comment]
+1

**Comment by Krzysztof-Cieslak** [comment]
Closed by #5
