### ISSUE TITLE
memory drain when using 

### ISSUE THREAD

**Issue by Delli** [sbrink/vscode-elm#23]
after a while  my computer complains memory low 
in the task manager there are then substantial cmd prompts running.
closing vscode resolves the issue.

suspect the plugin restart the cmd prompt after every autosave ?

**Comment by stkb** [comment]
I'm keeping an eye on this but I'm not seeing this behaviour on my machine. If you're seeing lots of instances of cmd in the task manager, could you take a look at what the command line is for them?
