### ISSUE TITLE
elm-repl does not start within VSCode ..

### ISSUE THREAD

**Issue by StefanHub** [sbrink/vscode-elm#27]
.. it only displays an empty "Output".
Probably something simple, but I don't get.

My environment:
- Win 8.1
- nodejs 5.5.0
- elm repl 0.16.0 (starts from the command line)
- VSCode 0.10.6

**Comment by stkb** [comment]
Did you install elm via NPM? Some stuff, including the repl, doesn't work on Windows if you do that. I'm working on a fix right at the moment.

**Comment by StefanHub** [comment]
Yes, I installed elm via NPM. Btw, I installed NPM via scoop (https://github.com/lukesampson/scoop)

**Comment by stkb** [comment]
It's a classic problem, the extension is looking for "elm-repl" on your path, but if you install with npm then that doesn't exist, only "elm-repl**.cmd**". 

For now, if you want, you can try uninstalling the npm package (```npm uninstall -g elm```) and install Elm via [the Windows installer](http://elm-lang.org/install) instead.  But as I say, I'm working on fixing this, as well as cleaning up the code here, and should have a PR for it in the next couple of days.

**Comment by StefanHub** [comment]
I will wait :-)
