### ISSUE TITLE
elm-make fails with path containing spaces

### ISSUE THREAD

**Issue by villasv** [sbrink/vscode-elm#28]
I know using spaces in folders is a recipe for disaster, but that is very common on Windows if the user is set with full names (like mine: `C:\Users\Victor Villas`).
In this case, elm-make fails and it inutilizes some of the package functionalities.

Note that if I use the command Elm: Make (Ctrl+F5) manually it works, but nevertheless the background checking does not.

![](http://i.imgur.com/FdmQ39H.jpg)

**Comment by villasv** [comment]
What I could trace down after reading the source files is the following:

The `runMake` command runs elm-make through a child process like this:

    function runMake(editor : vscode.TextEditor) : void {
        (...)
        const file = editor.document.fileName
        make = cp.spawn('elm-make', [file,'--yes', '--output=' + name], {cwd: cwd})

The linter in the other hand, goes somewhat different:

    function checkForErrors(filename): Promise<IElmIssue[]> {
        (...)
        let cmd: string = 'elm-make ' + filename + ' --report=json --output /dev/null';
        (...)
    }
    
    export function runLinter(document: vscode.TextDocument): void {
    let uri: vscode.Uri = document.uri;
    checkForErrors(uri.fsPath)
    (...)
    }

I suspect that `spawn` automatically handles paths with spaces, while manually concatenating the filename in the `checkForErrors` does not.

**Comment by stkb** [comment]
Thanks. You are right, and I've done a done a quick fix for it in #31
