### ISSUE TITLE
Detect elm root path correctly

### ISSUE THREAD

**Issue by sbrink** [sbrink/vscode-elm#3]
At the moment the current project path is set to the directory of the file.

@rojepp took the vscode.workspace.rootPath.

I think both approaches are not sufficient.

The best way would probably to search for elm-package.json in the current and parent folders.

**Comment by rojepp** [comment]
Agreed, it should search upwards recursively until rootpath.

mån 23 nov. 2015 00:03 Sascha Brink <notifications@github.com> skrev:

**Comment by peacememories** [comment]
+1

This is particularly annoying right now because saving an .elm file automatically creates an elm-package.json in the same directory.

**Comment by sbrink** [comment]
@peacememories From Saturday on I'll have 3 weeks for elm hacking.

So I'll fix this on saturday and hope you can wait 2 more days :)

**Comment by peacememories** [comment]
I'm not in much of a hurry right now, my current project is small enough to live in one directory.
Thanks for responding so quickly =)

**Comment by Krzysztof-Cieslak** [comment]
I've PR fix to that #13. Waiting for review.

**Comment by Krzysztof-Cieslak** [comment]
#13 Merged, now waiting for release :)

**Comment by sbrink** [comment]
give me a few minutes, will release asap :)

maybe we should use codeship or travisCI for building + release
