### ISSUE TITLE
Error hover needs line wrapping

### ISSUE THREAD

**Issue by thSoft** [sbrink/vscode-elm#30]
As of version 0.3.0, inline error messages are not line wrapped, which makes them hard to read.

**Comment by stkb** [comment]
I'm not certain but I think wrapping for hovers is a vscode issue that's been [fixed](https://github.com/Microsoft/vscode/commit/db1316eba59d0006edce0ad5cc1afcca49c10b32) for the next release.

**Comment by thSoft** [comment]
Yes, this seems like a VSCode issue.
