### ISSUE TITLE
Integrate elm-format

### ISSUE THREAD

**Issue by toburger** [sbrink/vscode-elm#32]
Would be nice to have [elm-format](https://github.com/avh4/elm-format) support in vscode.
I've used it in Atom and I must admit, I'm addicted now!

**Comment by stkb** [comment]
Yeah this could be added, I think as a ```DocumentFormattingEditProvider``` (which then gets invoked with ```shift+alt+f```). Since elm-format doesn't have an npm distribution yet I guess we should just look for ```elm-format``` on the user's path and use it if it's there. If it's not there then nothing will happen (just like now).
