### ISSUE TITLE
Enhancing the elm dependencies install command

### ISSUE THREAD

**Issue by stkb** [sbrink/vscode-elm#36]
I think enhancing the "install dependencies" command into something like this would be pretty neat:
![depall1](https://cloud.githubusercontent.com/assets/6125444/13196001/811b3444-d7c2-11e5-8ad4-e595a906ac71.png)

As it says in the input placeholder, you can just press  ```<esc>``` to install all packages already listed in ```elm-package.json``` (as the command currently works now), or pick a new package to install.

It *could* be done as a separate command, but I kinda wanted to avoid that, since I kinda feel the extension has too many commands already :)

Just wondering what other's input was.

**Comment by Krzysztof-Cieslak** [comment]
PR merged and released
