### ISSUE TITLE
Continually crashing

### ISSUE THREAD

**Issue by keepitreal** [sbrink/vscode-elm#41]
After installing this plugin, I can't seem to edit an elm file for more than a couple of keystrokes without it crashing the VS Code window. I'm sorry I can't provide any specific detail except that I'm running VS Code 0.10.10 on OS X El Capitan.

Here's a screenshot after the crash
<img width="520" alt="screen shot 2016-03-10 at 10 47 34 pm" src="https://cloud.githubusercontent.com/assets/2781807/13693608/48afe8d4-e712-11e5-97a7-81109998893a.png">

**Comment by greyepoxy** [comment]
I am seeing the same thing but on Windows 10. Tried to get crash information with the debug window but it kept disconnecting on the crash.

**Comment by stkb** [comment]
Are you guys editing .elm files that are outside of an elm project? (ie: a folder with elm-package.json, elm-stuff/ etc)

This is related to vscode v0.10.10 being crashy in some circumstances (related Microsoft/vscode#3963)  and I think a bug with the autocomplete feature of the extension.

I was planning on fixing this as part of a larger update to autocomplete but can move a fix forward.

**Comment by greyepoxy** [comment]
Hmm in my case I was not. In a project setup like this one https://github.com/greyepoxy/elm-webpack-skeleton I was just editing elm files in the src folder.

**Comment by stkb** [comment]
Hmm I can't reproduce the exact issue but I've submitted PR #42 which I know fixes an issue that can cause crashes.

However in the mean time could you try the fix yourself by installing [this .vsix file](https://github.com/sbrink/vscode-elm/files/168607/elm-crash-fix.zip)? (a vsix is simply a packaged version of an extension)

You need to first uninstall the elm extension from vscode. 
Then unzip that file, and in the unzipped folder folder, run:
```
code elm-crash-fix.vsix
```

**Comment by mickeyvip** [comment]
@stkb, thank you.

The VSCode (v`0.10.10` on El Capitan) now works without crashing.

**Comment by greyepoxy** [comment]
The fix seems to work for me as well! Thanks @stkb

**Comment by brobrts** [comment]
I have VSCode Version 0.10.11 (0.10.11) and it is crashing every time a make an edit.  This only happens with elm  projects.

**Comment by brobrts** [comment]
My apologies!!  That also fixed it for me.

**Comment by stkb** [comment]
@sbrink @Krzysztof-Cieslak or @rojepp Could you take a look at #42? (and other PR's)

**Comment by keepitreal** [comment]
The latest update has fixed this. Thanks!

**Comment by Krzysztof-Cieslak** [comment]
I think we can close, I've merged everything and released new version to marketplace. Sorry for problem!
