### ISSUE TITLE
elm-make is not recognized as an internal or external command ... 

### ISSUE THREAD

**Issue by RobertWalter83** [sbrink/vscode-elm#44]
In a new elm file, I get an error marker when I have code in the very first line:

![image](https://cloud.githubusercontent.com/assets/5462981/13950599/44235e18-f02c-11e5-8e2d-c4b65d8585d5.png)

Adding a newline on top removes the marker.

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed by #63
