### ISSUE TITLE
Feature Request: Format on Save

### ISSUE THREAD

**Issue by zolrath** [sbrink/vscode-elm#46]
It would be nice if there was an option to run elm-format on save instead of needing to explicitly run the format command.
This was implemented in vscode-go here: https://github.com/Microsoft/vscode-go/pull/115

**Comment by stkb** [comment]
Seems like a reasonable request. Thanks for the go link too.

**Comment by abadi199** [comment]
I implemented this feature on my [elm-format](https://marketplace.visualstudio.com/items?itemName=abadi199.elm-format) extensions. I'll make a PR when I have free time to do it.

**Comment by kylecordes** [comment]
By the way, I found it very strange that there is an Elm plug-in with most of the Elm features, but then this one free-floating extra plug-in for just the Elm format feature. Stranger still, the following commit seems to add Elm format support to this main plug-in, but I don't actually see the feature available anywhere.

https://github.com/sbrink/vscode-elm/commit/4f892bf20a1ce4344c0cce1f00eed303866f7ced

For the sake of the next reader here, the answer to this (small) mystery is: the feature is now present in this main Elm extension. As far as I can tell you don't need the other separate format extension anymore, although I much appreciate @abadi199 for providing the feature in the meantime. You won't see anything about "elm format" in the command-whatever-P menu, rather it is fully integrated into VSCode. Just press the same shift-alt-F you would press to format any other file in its appropriate language syntax.

**Comment by Krzysztof-Cieslak** [comment]
Fixed by #62
