### ISSUE TITLE
Suddenly things aren't being red squiggly underlined

### ISSUE THREAD

**Issue by ccapndave** [sbrink/vscode-elm#48]
A few weeks ago Elm errors stopped being underlined with a red squiggly line, even though a separate compiler (in a console) shows errors.  I think it might have happened after the last update of VSCode.  Any ideas how I can debug this?

**Comment by ccapndave** [comment]
P.S. Its not all errors; just some (I know this isn't very helpful, but its not clear what the difference is between errors it is catching and errors it isn't)

**Comment by stevensona** [comment]
By any chance are you on Windows? #63 addresses some issues I had and may be related.

**Comment by ccapndave** [comment]
No, I'm on OSX.  Now that I've had more time I think it might be related to extra dirs included in `elm-package.json` in `source-directories`, but I'm still not 100% sure.

**Comment by svoynow** [comment]
Having the same issue. It does seem to have to do with `source-directories`. Everything worked fine when I only had one file, once I broke it up into multiple files, I needed to add my `./src` directory to `source-directories` and that's when it stopped working.
Does the extension make any assumptions about project structure?

**Comment by ccapndave** [comment]
I just found today that this is caused by my subpackages defined in `source-directories` not having everything that is required in its `elm-packages.json`.  When I went through very carefully making sure that everything required by the subpackage is in there, then did an `elm-package install`, red squigglies started working properly!
