### ISSUE TITLE
Auto-complete for current project files

### ISSUE THREAD

**Issue by kunjee17** [sbrink/vscode-elm#49]
After updating to latest version. Auto complete is working great for all package I m importing. But for the files and modules I have added I can't find auto-complete. 

Am I missing here something?

**Comment by Krzysztof-Cieslak** [comment]
Unfortunately, that's limitation of [elm-oracle](https://github.com/ElmCast/elm-oracle).

**Comment by kunjee17** [comment]
@Krzysztof-Cieslak Oh ok. No problem. Thanks for reply.
