### ISSUE TITLE
allow `Elm: Make` to take in `--output` parameter

### ISSUE THREAD

**Issue by theburningmonk** [sbrink/vscode-elm#50]
Not sure if this is even possible with VS Code's plugin infrastructure but it'll be nice to be able to set the `--output` parameter when running the `Elm: Make` command rather than having to change the workspace setting when switching between projects with different conventions.

**Comment by wmakley** [comment]
How did you change the workspace setting?

I am going a little crazy because the linter in this extension interferes with elm make. I have to blow away my build-artifacts directory when I want to actually compile and test the results in a browser using my pre-existing build script. :-/

**Comment by Krzysztof-Cieslak** [comment]
@wmakley: File |> Preferences |> Workspace settings

@theburningmonk: Workspace settings are per project (saved in local `.vscode\settings.json` file) so it shouldn't be huge problem. I guess it might be bit annoying, but I think it's most reasonable way of doing it.
