### ISSUE TITLE
In Code 1.1.0, format duplicates content

### ISSUE THREAD

**Issue by bdukes** [sbrink/vscode-elm#54]
When running the format command on an elm file in VS Code 1.1.0, the formatted code is added at the beginning of the file, but the old code is still there after the formatted code.

**Comment by kylecordes** [comment]
I am running the current vscode-elm and VSCode 1.2.0-insider right now and used the format feature on a number of files and did not see any duplication of contents. Therefore from this one data point, the above fix worked. I don't know if more confirmation is needed to call the item done or not. Hope this helps.

**Comment by Krzysztof-Cieslak** [comment]
Yes, thanks. This should be closed :)
