### ISSUE TITLE
linter and elm-make not working in windows when elm installed via NPM

### ISSUE THREAD

**Issue by Oustad** [sbrink/vscode-elm#58]
Hi, 

Had some issues getting the linting on save to work.
After som digging and debugging of the extension I found that the problem was I installed elm via npm.
Which only gives an elm-make.cmd file in C:\Users\someuser\AppData\Roaming\npm.
Saving the file gives the following error "The 'elm-make' compiler is not available.  Install Elm from http://elm-lang.org/." from https://github.com/sbrink/vscode-elm/blob/master/src/elmLinter.ts#L69

I tested changing https://github.com/sbrink/vscode-elm/blob/master/src/elmLinter.ts#L45 to 
` const make: cp.ChildProcess = cp.spawn('elm-make.cmd', [filename, '--report', 'json', '--output', '/dev/null'], { cwd: cwd }); ` which works. But that would not work for every case.

Removing the npm installed elm and installing with the installer and everything works perfectly

**Comment by stevensona** [comment]
Fixed by #63

**Comment by Krzysztof-Cieslak** [comment]
Fixed by #63
