### ISSUE TITLE
Implement "Elm: Clean" command.

### ISSUE THREAD

**Issue by abadi199** [sbrink/vscode-elm#68]
Because of the [bug](https://github.com/elm-lang/elm-make/issues/107) in `elm-make`, I occasionally have to delete the `elm-stuff/build-artifacts/` folder, and switching to terminal to do that is not a great experience. 

I'm thinking of implementing a new command called `Elm: Clean` that will delete the `elm-stuff/build-artifacts/` folder.

Let me know if you think this will be valuable, and I'll create a PR for this.

**Comment by gaborv** [comment]
I like the idea.

**Comment by wmakley** [comment]
I just tried to use this (on Ubuntu) and got a generic error with no further details. Does it need to be changed for Elm 0.19?

**Comment by abadi199** [comment]
Yes, the folder for the build artifacts is changed to `elm-stuff/0.19.0`. Any reason why you still need to clean build artifacts in Elm 0.19? If you feel it's still valuable to have this feature on Elm 0.19, I recommend to create a new issue for this.

**Comment by wmakley** [comment]
Because there is a bug in the Elm compiler that is causing it to emit bad build artifacts in complicated projects that I hit constantly: https://github.com/elm/compiler/issues/1837

Sometimes the linter runs into the same bug and stops working for a while.

I will make a new issue, thanks!
