### ISSUE TITLE
Idea: Use debugger for REPL

### ISSUE THREAD

**Issue by sbrink** [sbrink/vscode-elm#7]
Hey @Krzysztof-Cieslak @rojepp ,

the starting the REPL from a file is awesome. Maybe we could go even one step further.
In VS Code the debugger allows an interactive shell. Do you think its a good idea to use
this for an interactive REPL? 

There's a mock example for VS Code: https://github.com/Microsoft/vscode-mock-debug

**Comment by Krzysztof-Cieslak** [comment]
We have started issue for adding extension endpoint for interactive shell / REPL - https://github.com/Microsoft/vscode/issues/547

**Comment by sbrink** [comment]
Ah, this would definitely be the best solution. Closing this one for now. Thanks for the info/update.
