### ISSUE TITLE
Sort the import statements when format the code

### ISSUE THREAD

**Issue by lijunle** [sbrink/vscode-elm#83]
Hi,

This is an awesome tool. Thank you for creating this tool. I have a feature request, is it possible to sort the import statements when format the code?

**Comment by hakonrossebo** [comment]
Formatting is handled in elm-format and there is an ongoing discussion here https://github.com/avh4/elm-format/issues/8. I suggest that this issue should be closed.

**Comment by Krzysztof-Cieslak** [comment]
Agree

**Comment by lijunle** [comment]
Thank you for information. I will follow that thread.
