### ISSUE TITLE
Clarify autocompletion support

### ISSUE THREAD

**Issue by wolverian** [sbrink/vscode-elm#86]
The README is fairly confusing on this issue:

<img width="200" alt="screen shot 2016-11-18 at 15 45 56" src="https://cloud.githubusercontent.com/assets/42124/20432079/1ec8132e-ada6-11e6-82a8-32eecddf63d5.png">

It's TODO, but it's marked done. 😕 🙃😅 Which is it?

**Comment by Krzysztof-Cieslak** [comment]
It's done. Thanks for pointing out problem in Readme :)
