### ISSUE TITLE
"Cannot read property 'substring' of undefined" when running elm-format

### ISSUE THREAD

**Issue by martincerny** [sbrink/vscode-elm#89]
This is probably not a bug in vscode-elm, but I am filing it here to make it easier for others to find.
What's going on: after an update to VS Code 1.8.1, pressing Alt + Shift + F to format an elm document shows a warning: "Cannot read property 'substring' of undefined"

The same problem has been reported from formatting extensions for other languages:
https://github.com/Microsoft/vscode-go/issues/690
and has been filed to VS Code
https://github.com/Microsoft/vscode/issues/17424

I am currently looking for a workaround and will post here if I find any.

**Comment by martincerny** [comment]
OK, so the problem has been fixed and VS Code 1.9.0 should have it working again. In the meantime, installing the Insiders build of VS Code does the trick: https://code.visualstudio.com/insiders

**Comment by Krzysztof-Cieslak** [comment]
Thanks for info. :)
